nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://127.0.0.1:4200']
        allow_headers: ['Authorization', 'append', 'delete', 'entries', 'foreach', 'get', 'has', 'keys', 'set', 'values']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:4200']
            allow_headers: ['X-Custom-Auth', 'Authorization', 'append', 'delete', 'entries', 'foreach', 'get', 'has', 'keys', 'set', 'values']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['http://127.0.0.1:4200']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']
